apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
spec:
  params:
  - name: url
    value: IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api
  type: image
