apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: vote-app-placementrule
  namespace: acm
  labels:
    app: vote-app
spec:
  clusterSelector:
    matchLabels: {}
#      environment: Dev
