apiVersion: v1
kind: Namespace
metadata:
  name: vote-app-project
  labels:
    app: vote-app  
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: vote-app-channel
  namespace: vote-app-project
  labels:
    app: vote-app
spec:
  type: Git
  pathname: https://github.com/sjbylo/flask-vote-app.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: vote-app-placementrule
  namespace: vote-app-project
  labels:
    app: vote-app
spec:
  clusterSelector:
    matchLabels: {}
#      environment: Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: vote-app-subscription
  namespace: vote-app-project
  annotations:
    apps.open-cluster-management.io/git-path: deploy
    apps.open-cluster-management.io/git-branch: master
  labels:
    app: vote-app
spec:
  channel: vote-app-project/vote-app-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: vote-app-placementrule
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: vote-app-application
  namespace: vote-app-project
  labels:
    app: vote-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: vote-app
